name: Another workflow
on: push
jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  test:
    name: use secrets
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: |
          echo "my key " ${{ secrets.MY_KEY }}
